from django.db import models

class Book(models.Model):
  # ID auto generated by django
  title = models.CharField(max_length=255)
  desc = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  # authors attribute added

class Author(models.Model):
  # ID auto generated by django
  first_name = models.CharField(max_length=45)
  last_name = models.CharField(max_length=45)
  books = models.ManyToManyField(Book, related_name="authors")
  notes = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)